### ISSUE TITLE
Timestamp question

### ISSUE THREAD

**Issue by wir3dal** [FoxxMD/tautulli-notification-digest#5]
Not necessarily an issue with TND but I'm seeing the UTC time at the bottom of the discord digest and not sure where it's coming from. I'm running all of the apps as docker containers (Plex, Tautulli, TND) with the TZ environment variable set. Any thoughts on how to get the local time instead of UTC time?![Screenshot_20230902-121626~2.png](https://github.com/FoxxMD/tautulli-notification-digest/assets/119820780/42891e7d-80a9-439d-bc3e-b3caad3cffd8)

**Comment by FoxxMD** [comment]
I'll look into this. Do you have `TZ` set for Tautulli as well?

**Comment by wir3dal** [comment]
Yep, all 3 containers have TZ set

**Comment by FoxxMD** [comment]
@wir3dal I've removed timestamps from the embeds. It doesn't make sense to have them there since they'll never coincide with the scheduled posting time anyway. And if used with dedup behavior may still look wrong (even if they are right).

Try the `main` branch or newest `foxxmd/tautulli-notification-digest:latest` docker image

**Comment by wir3dal** [comment]
Thanks!
